#!/usr/bin/env bash
# bgrpiimage-boot: build-time adapter. Logic lives in apply.sh.
set -x
set -e
export LC_ALL=C

source /common.sh
install_cleanup_trap

unpack /filesystem/root / root

BGRPI_CTX=image /opt/bgrpiimage/bgrpiimage-boot/apply.sh
