#!/usr/bin/env bash
# BAUER GROUP XPD-RPIImage - local image build driver.
#
# Steps:
#   1. Resolve variant JSON + render generated files into src/modules/*/files/_generated
#   2. Ensure CustomPiOS is cloned
#   3. Link ./src into CustomPiOS and invoke its build in a privileged Docker container
#   4. Copy the resulting .img[.xz] into ./dist/
#
# Usage:
#   scripts/build.sh canbus-plattform                       # default variant
#   scripts/build.sh --env-file .env canbus-plattform
#   VARIANT=canbus-plattform scripts/build.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ENV_FILE=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --env-file) ENV_FILE="$2"; shift 2 ;;
        -h|--help) sed -n '1,20p' "$0"; exit 0 ;;
        *) VARIANT="$1"; shift ;;
    esac
done
VARIANT="${VARIANT:-canbus-plattform}"
CONFIG_JSON="config/variants/${VARIANT}.json"

if [[ ! -f "$CONFIG_JSON" ]]; then
    echo "error: $CONFIG_JSON not found" >&2
    exit 2
fi

echo "[build] rendering variant '$VARIANT'"
PY_ARGS=("$CONFIG_JSON")
[[ -n "$ENV_FILE" ]] && PY_ARGS=(--env-file "$ENV_FILE" "${PY_ARGS[@]}")
python3 scripts/generate.py "${PY_ARGS[@]}"

echo "[build] ensuring CustomPiOS"
bash scripts/bootstrap.sh
chmod +x "$ROOT/src/build_dist"
mkdir -p dist

# ---------------------------------------------------------------------------
# Download + pre-extract the raspios base image.
#
# CustomPiOS itself only understands `.zip` bundles (it shells out to 7za)
# while current Raspberry Pi OS is distributed as `.img.xz`.  We fetch the
# URL from the variant JSON ourselves, unxz once, and point BASE_ZIP_IMG
# at the cached raw `.img`.  CustomPiOS takes the ".img$" path (just cp)
# instead of the 7za extraction path - and crucially keeps our cached copy
# intact because it wipes `*.img` only from BASE_WORKSPACE.
# ---------------------------------------------------------------------------
echo "[build] preparing base image for '$VARIANT'"
IMAGE_URL=$(python3 - <<PY
import json
from pathlib import Path
cfg_path = Path("$CONFIG_JSON").resolve()
cfg = json.load(open(cfg_path))
seen = set()
while "extends" in cfg and cfg_path not in seen:
    seen.add(cfg_path)
    parent_rel = cfg.pop("extends")
    cfg_path = (cfg_path.parent / parent_rel).resolve()
    parent = json.load(open(cfg_path))
    parent.update({k: v for k, v in cfg.items() if v is not None})
    cfg = parent
print(cfg["base_image"]["url"])
PY
)
echo "[build] URL: $IMAGE_URL"

CACHE="$ROOT/src/image-cache"
mkdir -p "$CACHE"
IMG_XZ="$CACHE/$(basename "$IMAGE_URL")"
IMG_RAW="${IMG_XZ%.xz}"

if [[ ! -f "$IMG_XZ" && ! -f "$IMG_RAW" ]]; then
    echo "[build] downloading $IMG_XZ"
    curl -fSL --retry 3 -o "$IMG_XZ.partial" "$IMAGE_URL"
    mv "$IMG_XZ.partial" "$IMG_XZ"
fi
if [[ -f "$IMG_XZ" && ! -f "$IMG_RAW" ]]; then
    echo "[build] unxz $IMG_XZ"
    xz -d --keep "$IMG_XZ"
fi

# CustomPiOS's custompios script wipes *.img from BASE_WORKSPACE right at
# the start, so we MUST NOT put our cached copy there.  Instead hand it
# the path via BASE_ZIP_IMG; CustomPiOS sees the ".img$" suffix and falls
# into the `cp "$BASE_ZIP_IMG" .` branch, copying it into the workspace.
#
# config.local is sourced LAST by CustomPiOS (after dist-config, board,
# variant, flavor) so we override the auto-loaded raspios_lite_arm64
# variant which sets its own BASE_ZIP_IMG to an empty .zip glob.  The
# path uses $DIST_PATH so it resolves correctly in both native (host)
# and docker (container) runs.
CACHE_REL="image-cache/$(basename "$IMG_RAW")"
cat > "$ROOT/src/config.local" <<EOF
# Auto-generated by scripts/build.sh - do not edit, will be overwritten.
export BASE_ZIP_IMG="\${DIST_PATH}/${CACHE_REL}"
EOF
echo "[build] config.local: BASE_ZIP_IMG=\${DIST_PATH}/${CACHE_REL}"

# Two build paths:
#   BGRPI_NATIVE_BUILD=yes  -> run directly on the host (CI runners, bare
#                              Linux dev boxes). No image pull, no privileged
#                              sibling container. Assumes qemu-user-static /
#                              kpartx / xz / sfdisk are already installed.
#   unset / no              -> run inside guysoft/custompios sibling container.
#                              For local dev on macOS, Windows, or when the
#                              host lacks build tooling.
if [[ "${BGRPI_NATIVE_BUILD:-no}" == "yes" ]]; then
    echo "[build] native mode (no docker) for variant '$VARIANT'"
    bash "$ROOT/CustomPiOS/src/update-custompios-paths" "$ROOT/src"
    ( cd "$ROOT/src" && bash ./build_dist "$VARIANT" )
else
    DOCKER_IMAGE="${DOCKER_IMAGE:-guysoft/custompios:devel}"
    echo "[build] launching container $DOCKER_IMAGE for variant '$VARIANT'"
    # update-custompios-paths must run INSIDE the container so the
    # custompios_path sidecar records /distro/CustomPiOS/src (the bind-mount
    # path) instead of the host's absolute path.
    docker run --rm --privileged \
        --volume "$ROOT":/distro \
        --workdir /distro/src \
        "$DOCKER_IMAGE" \
        bash -c "bash /distro/CustomPiOS/src/update-custompios-paths /distro/src \
                 && ./build_dist ${VARIANT}"
fi

# CustomPiOS leaves the image in workspace-<variant> for non-default variants.
for ws in "$ROOT/src/workspace-${VARIANT}" "$ROOT/src/workspace"; do
    [[ -d "$ws" ]] || continue
    IMG=$(ls -1 "$ws"/*.img 2>/dev/null | head -n1 || true)
    [[ -n "$IMG" ]] && break
done
if [[ -z "${IMG:-}" ]]; then
    echo "error: no .img produced (looked in workspace-${VARIANT} and workspace)" >&2
    exit 1
fi

# Derive version + optional suffix for the output filename.
#   VERSION       - from env (CI sets it) or parsed from the variant JSON
#   IMAGE_SUFFIX  - appended after the version, e.g. '-abc1234' for push
#                   builds; empty for tag releases so the asset is clean.
if [[ -z "${VERSION:-}" ]]; then
    VERSION=$(python3 - <<PY
import json, sys
try:
    print(json.load(open("$CONFIG_JSON"))["variant"].get("version", "0.0.0"))
except Exception:
    print("0.0.0")
PY
)
fi
SUFFIX="${IMAGE_SUFFIX:-}"

OUT="dist/bgrpiimage-${VARIANT}-v${VERSION}${SUFFIX}.img"
cp -v "$IMG" "$OUT"
echo "[build] compressing"
xz -T0 -f "$OUT"
echo "[build] done -> ${OUT}.xz"

# When CI invokes us via `sudo -E` (needed for loop devices / kpartx /
# chroot), dist/ ends up owned by root. The next workflow steps
# (sha256sum, upload-artifact) run as the regular runner user and
# cannot write into dist/ - they fail with "Permission denied".
# Hand the output directory back to the invoking user so post-build
# steps work without another sudo. Also covers image-cache/ + workspace-*
# which contain many files the runner user might want to clean later.
if [[ "${EUID:-$(id -u)}" -eq 0 && -n "${SUDO_UID:-}" && -n "${SUDO_GID:-}" ]]; then
    echo "[build] handing ownership back to ${SUDO_USER:-uid ${SUDO_UID}}"
    chown -R "${SUDO_UID}:${SUDO_GID}" dist "$ROOT/src/image-cache" "$ROOT/src/workspace-${VARIANT}" 2>/dev/null || true
fi
